site_name: Gillian Florence
site_url: https://sitename.example
theme:
  name: material
  palette:
    scheme: default
    primary: indigo
    accent: deep purple
  font:
      text: Roboto
  features:
    - toc.integrate
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - SFS-X Installation: installation.md 
  - Working Alone Timer: 
    - Overview: wat-overview.md
    - Metadata: wat-metadata.md
    - Configuration: 
      - Overview: wat-configuration.md
      - Set Up Service Resources and Service Territories: wat-config-setup-service-resource.md
  - Union Rules: 
    - Overview: unionrules-overview.md
    - Metadata: 
      - Custom Objects: unionrules-metadata-customobjects.md
      - Flows: unionrules-metadata-flows.md
    - Configuration: unionrules-configuration.md
  
markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences